/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/auth/formItem/Account.vue')['default']
    AuthDialog: typeof import('./src/components/dialog/AuthDialog.vue')['default']
    AuthForm: typeof import('./src/components/auth/form/AuthForm.vue')['default']
    CheckCode: typeof import('./src/components/auth/formItem/CheckCode.vue')['default']
    CustomDialog: typeof import('./src/components/dialog/CustomDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    EmailCode: typeof import('./src/components/auth/formItem/EmailCode.vue')['default']
    EmailCodeDialog: typeof import('./src/components/dialog/EmailCodeDialog.vue')['default']
    ForgetForm: typeof import('./src/components/auth/form/ForgetForm.vue')['default']
    LoginForm: typeof import('./src/components/auth/form/LoginForm.vue')['default']
    Password: typeof import('./src/components/auth/formItem/Password.vue')['default']
    RegForm: typeof import('./src/components/auth/form/RegForm.vue')['default']
    Remember: typeof import('./src/components/auth/formItem/Remember.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitForm: typeof import('./src/components/auth/formItem/SubmitForm.vue')['default']
    Username: typeof import('./src/components/auth/formItem/Username.vue')['default']
  }
}
